[project]
name = "dWallet"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/home/runner/multisig/dWallet/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.multi-signature]
path = "contracts/multi-signature.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
